import { useState } from "react";
import { CheckCircle2, Eye, ShieldCheck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

const display = (value: unknown) => value === null || value === undefined || value === "" ? "—" : String(value);

export default function AdminProfileReviews({ enabled }: { enabled: boolean }) {
  const utils = trpc.useUtils();
  const changes = trpc.admin.profileChanges.list.useQuery(undefined, { enabled });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [notes, setNotes] = useState("");
  const review = trpc.admin.profileChanges.review.useMutation({ onSuccess: () => { utils.admin.profileChanges.list.invalidate(); utils.admin.alumni.list.invalidate(); utils.publicData.alumniList.invalidate(); toast.success("Profile change review saved."); setSelectedId(null); setNotes(""); }, onError: error => toast.error(error.message) });
  if (!enabled) return <section className="admin-panel"><p className="eyebrow">PROFILE REVIEWS</p><h2>Administrator permission required.</h2><p className="admin-empty">Only a Super Administrator can approve or reject alumni-submitted profile updates.</p></section>;
  const selected = changes.data?.find(change => change.id === selectedId);
  const proposed = (selected?.proposedData || {}) as Record<string, unknown>;
  return <><section className="admin-section-head"><div><p className="eyebrow">PROFILE REVIEWS</p><h1>Approve profile updates.</h1><p>Alumni-submitted changes stay private until an administrator approves them.</p></div></section><section className="admin-panel profile-review-panel"><div className="profile-review-summary"><span><strong>{changes.data?.filter(change => change.status === "pending").length ?? 0}</strong> pending</span><span>{changes.data?.length ?? 0} total submissions</span></div><div className="admin-table-wrap"><table><thead><tr><th>Alumnus</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{changes.data?.map(change => <tr key={change.id}><td><strong>{change.fullName || "Alumni record"}</strong><small>{change.studentId || change.email || "Identity protected"}</small></td><td>{new Date(change.createdAt).toLocaleDateString()}</td><td><em className={`status status--${change.status === "pending" ? "draft" : change.status}`}>{change.status}</em></td><td><button className="table-link" onClick={() => setSelectedId(change.id)}><Eye size={14}/> Review</button></td></tr>)}</tbody></table></div>{!changes.data?.length && <p className="admin-empty">No alumni profile changes have been submitted.</p>}</section>{selected && <div className="profile-review-modal"><div className="profile-review-modal__body"><button className="profile-review-modal__close" onClick={() => setSelectedId(null)} aria-label="Close review">×</button><p className="eyebrow">ALUMNI PROFILE CHANGE</p><h2>{selected.fullName || "Alumni record"}</h2><p className="profile-review-modal__meta">Submitted {new Date(selected.createdAt).toLocaleString()} · Sensitive registered email and Alumni ID remain protected.</p><div className="profile-review-grid">{Object.entries(proposed).map(([key, value]) => <div key={key}><span>{key.replace(/([A-Z])/g, " $1").replace(/^./, char => char.toUpperCase())}</span><strong>{display(value)}</strong></div>)}</div><label className="profile-review-notes"><span>Review notes (optional)</span><textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Add a note for the alumni record…" /></label><div className="profile-review-actions"><button className="admin-action admin-action--muted" onClick={() => review.mutate({ id: selected.id, decision: "rejected", notes })}><XCircle size={15}/> Reject</button><button className="admin-action" onClick={() => review.mutate({ id: selected.id, decision: "approved", notes })}><CheckCircle2 size={15}/> Approve & publish update</button></div></div></div>}</>;
}
